// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLnKmkbh72hIRg64a4oYtBmPepMlzO4c',
    appId: '1:94404574753:web:5e9c32b28ab28285f52d60',
    messagingSenderId: '94404574753',
    projectId: 'mcq-app-8a733',
    authDomain: 'mcq-app-8a733.firebaseapp.com',
    storageBucket: 'mcq-app-8a733.appspot.com',
    measurementId: 'G-C8Y5SVDPCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZjvpm1VYrTrdx2yduTQ6Y2cpe08dtO8',
    appId: '1:94404574753:android:bdb1d4b1b2aa6627f52d60',
    messagingSenderId: '94404574753',
    projectId: 'mcq-app-8a733',
    storageBucket: 'mcq-app-8a733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXgxyrZBXcfeArQZG5oLal848X_eBK-s',
    appId: '1:94404574753:ios:63dc8ccf00e5666cf52d60',
    messagingSenderId: '94404574753',
    projectId: 'mcq-app-8a733',
    storageBucket: 'mcq-app-8a733.appspot.com',
    iosClientId: '94404574753-4oou8gb6ppiqlum4eordntbk7pq8ejli.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlXgxyrZBXcfeArQZG5oLal848X_eBK-s',
    appId: '1:94404574753:ios:63dc8ccf00e5666cf52d60',
    messagingSenderId: '94404574753',
    projectId: 'mcq-app-8a733',
    storageBucket: 'mcq-app-8a733.appspot.com',
    iosClientId: '94404574753-4oou8gb6ppiqlum4eordntbk7pq8ejli.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcq',
  );
}
